/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MessagesRouteRouteImport } from './routes/messages.route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CountIndexRouteImport } from './routes/count.index'
import { Route as MessagesMessageIdRouteImport } from './routes/messages.$messageId'
import { Route as CountTanstackRouteImport } from './routes/count.tanstack'
import { Route as CountElysiaRouteImport } from './routes/count.elysia'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRouteRoute = MessagesRouteRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CountIndexRoute = CountIndexRouteImport.update({
  id: '/count/',
  path: '/count/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesMessageIdRoute = MessagesMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => MessagesRouteRoute,
} as any)
const CountTanstackRoute = CountTanstackRouteImport.update({
  id: '/count/tanstack',
  path: '/count/tanstack',
  getParentRoute: () => rootRouteImport,
} as any)
const CountElysiaRoute = CountElysiaRouteImport.update({
  id: '/count/elysia',
  path: '/count/elysia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/messages': typeof MessagesRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/count/elysia': typeof CountElysiaRoute
  '/count/tanstack': typeof CountTanstackRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/count': typeof CountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/count/elysia': typeof CountElysiaRoute
  '/count/tanstack': typeof CountTanstackRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/count': typeof CountIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/messages': typeof MessagesRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/landing': typeof LandingRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/count/elysia': typeof CountElysiaRoute
  '/count/tanstack': typeof CountTanstackRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/count/': typeof CountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/messages'
    | '/landing'
    | '/signin'
    | '/signup'
    | '/count/elysia'
    | '/count/tanstack'
    | '/messages/$messageId'
    | '/count'
    | '/dashboard/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/signin'
    | '/signup'
    | '/count/elysia'
    | '/count/tanstack'
    | '/messages/$messageId'
    | '/count'
    | '/dashboard'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/messages'
    | '/_auth'
    | '/landing'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/count/elysia'
    | '/count/tanstack'
    | '/messages/$messageId'
    | '/count/'
    | '/dashboard/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MessagesRouteRoute: typeof MessagesRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LandingRoute: typeof LandingRoute
  CountElysiaRoute: typeof CountElysiaRoute
  CountTanstackRoute: typeof CountTanstackRoute
  CountIndexRoute: typeof CountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/count/': {
      id: '/count/'
      path: '/count'
      fullPath: '/count'
      preLoaderRoute: typeof CountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$messageId': {
      id: '/messages/$messageId'
      path: '/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof MessagesMessageIdRouteImport
      parentRoute: typeof MessagesRouteRoute
    }
    '/count/tanstack': {
      id: '/count/tanstack'
      path: '/count/tanstack'
      fullPath: '/count/tanstack'
      preLoaderRoute: typeof CountTanstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/count/elysia': {
      id: '/count/elysia'
      path: '/count/elysia'
      fullPath: '/count/elysia'
      preLoaderRoute: typeof CountElysiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface MessagesRouteRouteChildren {
  MessagesMessageIdRoute: typeof MessagesMessageIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteRouteChildren: MessagesRouteRouteChildren = {
  MessagesMessageIdRoute: MessagesMessageIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteRouteWithChildren = MessagesRouteRoute._addFileChildren(
  MessagesRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MessagesRouteRoute: MessagesRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LandingRoute: LandingRoute,
  CountElysiaRoute: CountElysiaRoute,
  CountTanstackRoute: CountTanstackRoute,
  CountIndexRoute: CountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
